### ISSUE TITLE
Update to pac4j 1.8

### ISSUE THREAD

**Issue by busybeaver** [bujiio/buji-pac4j#30]
Hi,

the current version of *buji-pac4j* is at the moment not compatible with *pac4j* 1.8

For instance the [``ClientUserFilter``](https://github.com/bujiio/buji-pac4j/blob/master/servlet/src/main/java/io/buji/pac4j/filter/ClientUserFilter.java#L50-L56) is not working due to API changes in the ``Client.redirect `` method (plus obviously fails if the client is a subclass of ``DirectClient``, since these don't support redirecting).
The ``ClientRolesAuthorizationFilter`` and ``ClientPermissionsAuthorizationFilter`` classes have similar issues.

Best,
busybeaver

**Comment by xRomZak** [comment]
+1
Trying to integrate CAS REST Client (DirectClient) from pac4j 1.8.

**Comment by leleuj** [comment]
I plan to do that in a few weeks and release a 1.4.0 version. As Shiro is already a security library, buji-pac4j will stay a multi-protocols authentication extension.
So the upgrade should be fairly straightfoward: only `IndirectClient` will be supported.

Feel free to submit a pull request.

**Comment by leleuj** [comment]
PR: https://github.com/bujiio/buji-pac4j/pull/31 and the demo: https://github.com/pac4j/buji-pac4j-demo/pull/9

It was not too complicated. It must be fully tested though.

@busybeaver @xRomZak : feedbacks?

**Comment by xRomZak** [comment]
Any plans for `DirectClient` support?

**Comment by leleuj** [comment]
No. Shiro is a security library which already handles authentication / authorization, buji-pac4j is an extension which complements it for multi-protocols support. Like spring-security-pac4j and cas-server-support-pac4j.
If you want to go further with pac4j, the idea is to choose an implementation for your framework which is a full security library: for simple J2E application -> j2e-pac4j, for a Spring Web MVC application -> spring-webmvc-pac4j, for Play: play-pac4j, and so on.

What's your development stack?

**Comment by xRomZak** [comment]
Shiro is planned to be used as a security framework in my application.
Currently I'm trying to find a proper solution to integrate CAS/SSO. 

CAS is located in another domain, where Spring Security is used to manage sessions (session cookies). Also there is a REST API behind the CAS (not CAS REST API itself) on the same domain. 

The main problem is how to access REST endpoint (CAS protected) in scope of SSO.
Maybe CAS proxy could help me, but I'm not sure.

**Comment by leleuj** [comment]
If you want to call a REST endpoint protected by CAS by an application protected by CAS, you should use the proxy mechanism. A good tutorial: https://wiki.jasig.org/display/CAS/Proxy+CAS+Walkthrough
