### ISSUE TITLE
getRoles() empty

### ISSUE THREAD

**Issue by dannymk** [bujiio/buji-pac4j#45]
Trying to get authorization to work properly in my shop.  As you can see below principal.getProfile().getRoles() is empty however the roles are part of the attributes.  Is there something missing in my configuration?

I would like to use these tags in my views:
`
<shiro:hasRole name="cas_admin">
            <h:outputText value="second===" />
            <br />
            <h:commandButton actionListener="${startShiro.logout()}" value="Logout" />
</shiro:hasRole>
`

This is a class method that I use to checkout the values in the principal
<pre>
...
public void verify(){
      try{
         final Pac4jPrincipal principal = SecurityUtils.getSubject().getPrincipals().oneByType(Pac4jPrincipal.class);  
         if (principal != null) {
            CommonProfile profile = principal.getProfile();
            logger.info("Email: " + profile.getEmail());
            logger.info("Roles: " + profile.getRoles().toString());
            logger.debug("Profile->roles: " + profile.getAttribute("roles"));
            
         }else{
            logger.info("NON Authenticated user: {}", principal);
            
         }
         
      }catch( Exception ex ){// just a general exception for now
         logger.error("Authorization failed."); 
        
      }
      
   }
...
</pre>

The output of the above code is...
...
Info:   INFO [http-listener-1(5)] (StartShiro.java:36) - Email: myemail@mydomain.com
Info:   INFO [http-listener-1(5)] (StartShiro.java:37) - Roles: []
Info:   DEBUG [http-listener-1(5)] (StartShiro.java:38) - Profile->roles: [cn=developers,cn=groups,cn=accounts,dc=mydomain,dc=com, cn=l2tp,cn=groups,cn=accounts,dc=mydomain,dc=com, cn=alfresco-users,cn=groups,cn=accounts,dc=mydomain,dc=com, cn=cas_admin,cn=roles,cn=accounts,dc=mydomain,dc=com, cn=ipausers,cn=groups,cn=accounts,dc=mydomain,dc=com]
...

My shiro.ini looks like:
<pre>
[main]
casClient = org.pac4j.cas.client.CasClient
casClient.casLoginUrl = https://cas.mydomain.com/cas/login

clients = org.pac4j.core.client.Clients
clients.callbackUrl = http://testservice.mydomain.com:8080/TestShiro/shiro-cas
clients.clients = $casClient

requireRoleAdmin = org.pac4j.core.authorization.authorizer.RequireAnyRoleAuthorizer
requireRoleAdmin.elements = ROLE_ADMIN

config = org.pac4j.core.config.Config
config.clients = $clients
config.authorizers = admin:$requireRoleAdmin

pac4jRealm = io.buji.pac4j.realm.Pac4jRealm

pac4jSubjectFactory = io.buji.pac4j.subject.Pac4jSubjectFactory
securityManager.subjectFactory = $pac4jSubjectFactory

casSecurityFilter = io.buji.pac4j.filter.SecurityFilter
casSecurityFilter.config = $config
casSecurityFilter.clients = CasClient

callbackFilter = io.buji.pac4j.filter.CallbackFilter
callbackFilter.config = $config
callbackFilter.multiProfile = true

[urls]
/secure/** = casSecurityFilter
/shiro-cas = callbackFilter
/logout = logout
/** = anon
</pre>

**Comment by leleuj** [comment]
In fact, roles are not linked to attributes by default. So in your case, you log in with CAS and there is a `role` attribute you need to turn into roles.

You have to create a specific `AuthorizationGenerator`:

```java
public class CustomAuthGenerator implements AuthorizationGenerator<CommonProfile> {

    @Override
    public void generate(CommonProfile profile) {
        String roles = profile.getAttribute("roles");
       for (String role: roles.split(",")) {
            profile.addRole(role);
       }
    }
}
```

and attach it to the `casClient`:  `casClient.authorizationGenerator = $customAuthGenerator`

**Comment by dannymk** [comment]
OK, got that working.  Is there an easy way to read the shiro.ini from within this customAuthGenerator?  I would like to use a mapping in the shiro.ini to split away all the information I do not need that is stored in the roles attributes.  Although it should not be there the information comes from an ldap directory so the string has the patternt "cn=developers,cn=groups,cn=accounts,dc=mydomain,dc=com".

**Comment by leleuj** [comment]
I have this `WebUtils` class in the demo: https://github.com/pac4j/buji-pac4j-demo/blob/master/src/main/java/org/pac4j/demo/shiro/WebUtils.java

Is this what you are looking for?

**Comment by dannymk** [comment]
OK, never mind, I figure out through the shiro.ini documentation and via various errors I got in the logs that this works:

in shiro.ini 
<pre>
[main]
ipaAuthGenerator = com.epcinstore.testshiro.IPAAuthGenerator
ipaAuthGenerator.sanitationPatterns = "cn=(.*),cn=groups,cn=accounts,dc=mydomain,dc=com","cn=(.*),cn=roles,cn=accounts,dc=mydomain,dc=com"

casClient = org.pac4j.cas.client.CasClient
casClient.casLoginUrl = https://buildcas.epc-instore.com/cas/login
casClient.authorizationGenerator = $ipaAuthGenerator
...
</pre>

Java class...
<pre>
package com.epcinstore.testshiro;
import java.util.LinkedList;
import org.pac4j.core.authorization.generator.AuthorizationGenerator;
import org.pac4j.core.profile.CommonProfile;
public class IPAAuthGenerator implements AuthorizationGenerator<CommonProfile> {
   private String[] sanitationPatterns;
   
   @Override
   public void generate(CommonProfile profile) {
      LinkedList<String> roles = (LinkedList<String>)profile.getAttribute("roles");
      for (String role : roles) {
         profile.addRole(cleanupIPARole(role));
      }
   }
   
   private String cleanupIPARole(String role){
      String[] patterns = getSanitationPatterns();
      for( String pattern : patterns ){
        role = role.replaceAll(pattern, "$1");
      }
      return role;
   }
   
   public void setSanitationPatterns(String[] pattern){
      this.sanitationPatterns = pattern;
   }
   
   public String[] getSanitationPatterns(){
      return this.sanitationPatterns;
   }
   
}
</pre>

and it works!

Don't worry so much about how simple the class is, I know I am making a ton of assumptions but at least I understand how to gel this all together.

**Comment by dannymk** [comment]
As a final note, once you understand the above you can use:

ipaAuthGenerator.sanitationPatterns = "^[^,]+=([^,]+).*"

as a catch all for "roles"
