### ISSUE TITLE
org.pac4j.core.authorization.authorizer.RequireAnyRoleAuthorizer does not accept multiple roles

### ISSUE THREAD

**Issue by dannymk** [bujiio/buji-pac4j#46]
The user has the role "cas_admin" but does not have the role "administrator".  
Per the documentation (https://github.com/pac4j/pac4j/wiki/Authorizers) the below should work but doesn't:
...
/secure/** = casSecurityFilter, roles[administrator, cas_admin]
...

This however works:
...
/secure/** = casSecurityFilter, roles[cas_admin]
...

**Comment by leleuj** [comment]
I'm not sure to understand what the problem is. pac4j authorizers apply via the `SecurityFilter` and `roles` is a default Shiro filter applied on the subject roles.
In both cases, all authorizers or roles are necessary to access the url.

**Comment by leleuj** [comment]
You can define multiple roles in the https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/authorization/authorizer/RequireAnyRoleAuthorizer.java and it will match if you have one of those roles.

**Comment by dannymk** [comment]
Well, the problem was in the definition of the elements, once you mentioned the authorizer I found an immediate solution:
...   
requireRoleAdmin = org.pac4j.core.authorization.authorizer.RequireAnyRoleAuthorizer
requireRoleAdmin.elements = [administrator, cas_admin]
...
config.authorizers = admin:$requireRoleAdmin
...
then it was just a matter of using the casSecurityFilter 
/secure/** = casSecurityFilter
...

It works, thank you for your help.

**Comment by aesyungan** [comment]
hep please

Error: authorizersMap['RequireAnyRoleAuthorizer'] cannot be null

**Comment by leleuj** [comment]
@aesyungan please use the mailing list for any questions

**Comment by aesyungan** [comment]
@leleuj  questions  https://groups.google.com/forum/#!topic/pac4j-users/cu5BYqP85Q4
