### ISSUE TITLE
Add a toString method to the Pac4jPrincipal class

### ISSUE THREAD

**Issue by leleuj** [bujiio/buji-pac4j#49]

**Comment by andre-doherty** [comment]
hello,
I would like to know if there is a reason (design ?) why Pac4jPrincipal doesn't implements java.security.Principal ? 
Maybe that's what you meant by this enhancement as the interface implies implementing a toString method.

I believe that the simple fact that Pac4jPrincipal implements that interface would ease the use of the principal object, eg on jsp/servlet level : 
In shiro core, when the principal object doesn't implements Principal it is wrapped into ShiroHttpServletRequest$ObjectPrincipal, which make its use a bit tricky : 
public Principal getUserPrincipal() {
        Principal userPrincipal;
        Object scPrincipal = getSubjectPrincipal();
        if (scPrincipal != null) {
            if (scPrincipal instanceof Principal) {
                userPrincipal = (Principal) scPrincipal;
            } else {
                **userPrincipal = new ObjectPrincipal(scPrincipal);**
            }
        } else {
            userPrincipal = super.getUserPrincipal();
        }
        return userPrincipal;
    }

**Comment by leleuj** [comment]
In fact, I only thought about the addition of the `toString` method, but your remark is relevant. Yes, we should implement `java.security.Principal`.

**Comment by andre-doherty** [comment]
OK i can create a pull request then.
I suppose something very simple such as : 
@Override
	public String getName() {
		CommonProfile profile = this.getProfile();
		return profile.getDisplayName();
		
	}
would be ok,
And of course the class implementing java.security.Principal

Maybe this code would need a control on profile being null but i am not quite sure this can happen

**Comment by leleuj** [comment]
The `getName()` is supposed to return some unique identifier, isn't it? In that case, it's better to use the `getId()` from the profile...

**Comment by andre-doherty** [comment]
OK then we would have : 
@Override
public String getName() {
	CommonProfile profile = this.getProfile();
	return profile.getId();	
}
	
@Override
public String toString() {
	return getName();
}
