### ISSUE TITLE
Spring xml support ?

### ISSUE THREAD

**Issue by albert-kam** [bujiio/buji-pac4j#5]
Apache shiro has support for spring xml to replace INI configuration.

Is buji-pac4j also supports spring xml configuration ? Or do i have to mix using INI and spring xml in my application ?

And if buji-pac4j supports it, do you mind putting a simple example about it ?

Thank you !

**Comment by leleuj** [comment]
Feel free to reopen if you didn't make it work with Spring (which I doubt)
