### ISSUE TITLE
Property 'casLoginUrl' does not exist for object of type org.pac4j.cas.client.CasClient

### ISSUE THREAD

**Issue by dannymk** [bujiio/buji-pac4j#53]
Property 'casLoginUrl' does not exist for object of type org.pac4j.cas.client.CasClient

--- Environment
java version "1.8.0_25"
Glassfish 4.1
O/S:  Mac Sierra - 10.12.3
...
```
        <dependency>
            <groupId>io.buji</groupId>
            <artifactId>buji-pac4j</artifactId>
            <version>2.0.4-SNAPSHOT</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.pac4j</groupId>
            <artifactId>pac4j-cas</artifactId>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.pac4j</groupId>
            <artifactId>pac4j-core</artifactId>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>
         <dependency>
             <groupId>org.apache.shiro</groupId>
             <artifactId>shiro-faces</artifactId>
             <version>2.0</version>
         </dependency>
```
...

--- shiro.ini
[main]
casClient = org.pac4j.cas.client.CasClient
casClient.casLoginUrl = https://cas.mydomain.com/cas/login

clients = org.pac4j.core.client.Clients
clients.callbackUrl = http://localhost:8080/TestShiro/shiro-cas
clients.clients = $casClient
...

Seems king of obvious what the error means but the documentation for this version does specify a "casLoginUrl" property in the shiro.ini file.

**Comment by leleuj** [comment]
You can't use pac4j v2 right now with buji-pac4j, it has not been upgraded although it may work.

CAS configuration has been moved to the `CasConfiguration` class where you have the `setLoginUrl` and `setPrefixUrl` methods.

**Comment by dannymk** [comment]
OK, thank you for the info.
