### ISSUE TITLE
Multi-factor Authentication

### ISSUE THREAD

**Issue by NBAMj** [bujiio/buji-pac4j#56]
Is there a way to implement 2-factor authentication with this library?

**Comment by leleuj** [comment]
Please ask your questions on the mailing-list: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users

Yes, you can implement 2-factor authentication, it's not out-of-the-box. pac4j allows you to have multiple user profiles at the same time, coming from different authentication processes (Facebook + Twitter for example). So you can create a specific Authorizer (http://www.pac4j.org/1.9.x/docs/authorizers.html) which checks the current user profiles retrieved via the [`ProfileManager`](https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/ProfileManager.java) and if "one factor is missing", you can decide to trigger this specific login process.
