### ISSUE TITLE
Pac4JPrincipal.getName() returns id

### ISSUE THREAD

**Issue by volumeint** [bujiio/buji-pac4j#61]
The Pac4JPrincipal class adapts the CommonProfile to implement java.security.Principal.  I would have expected getName() to return the value of getDisplayName or getUsername(), not getId().   I understand that Id is required and the other two values are not, but I would love to have seen the getName() method look for display_name or username before it returned the id.  Is that something you are open to changing?  I'm happy to create a pull request if it helps my cause.

**Comment by leleuj** [comment]
I haven't been able to confirm the information, but I had the feeling that the returned name should uniquely identify the principal. Yet, I'm not strongly tied to this implementation.

That said, reading the Zeppelin issue, I see this source code:

```java
public static String getPrincipal() {
    if (!isEnabled) {
      return ANONYMOUS;
    }
    Subject subject = org.apache.shiro.SecurityUtils.getSubject();
    String principal;
    if (subject.isAuthenticated()) {
      Object principalObj = subject.getPrincipal();
      if(principalObj instanceof Principal) {
        principal = ((Principal) principalObj).getName();
      } else {
        principal = String.valueOf(principalObj);
      }
    } else {
      principal = ANONYMOUS;
    }
    return principal;
  }
````

Why not use this simple following code to get the whole pac4j user profile and be able to get whatever your want?

```java
final PrincipalCollection principals = SecurityUtils.getSubject().getPrincipals();
if (principals != null) {
    final Pac4jPrincipal principal = principals.oneByType(Pac4jPrincipal.class);
    if (principal != null) {
        CommonProfile profile = principal.getProfile();
    }
}
```

There is nothing really interesting in the `Principal`,  you must get at least the `CommonProfile` (and why not the `OidcProfile`).

**Comment by volumeint** [comment]
Thanks for writing me back so soon and for reading the other pull request. 

Zeppelin doesn't currently include buji-pac4j as a compile-time dependency, I've been adding it to the classpath at runtime.  Zeppelin only compiles against Shiro and then relies upon realm implementations loaded via reflection based upon shiro.ini.  After adding buji-pac4j jars to the classpath, I was able to configure Shiro in Zeppelin to use the Pac4JRealm and through your library and Pac4J, I was able to authenticate using facebook, twitter and others.  The catch is that the Principal.getName() for facebook and twitter returns a numeric identifier and I expected to see a username.  

I appreciate your suggestion, but I can't cast the Principal to a Pac4jPrincipal or access the CommonProfile in the Zeppelin codebase unless buji-pac4j is a compile time dependency.   Right now, zeppelin only has access to the Shiro classes and those in the standard java packages.  Zeppelin reads the username and a list of roles from Shiro, so although Pac4J captures more information, Zeppelin isn't going to use it.

**Comment by leleuj** [comment]
OK. I see.

So I think the best solution is to configure buji-pac4j to tell it what to return for the name (keeping the identifier by default).
It could be done at the `Pac4jRealm` level when the `Pac4jPrincipal` is created. Something like:

`pac4jRealm.useDisplayNameForPrincipal = true`

Would you mind submitting a PR for that? Thanks

**Comment by volumeint** [comment]
I like the idea of setting something on the Pac4JRealm, that way it is configurable via shiro.ini.  What if instead of useDisplayNameForPrincipal=true, we allow them to specify the attribute name to pass to "CommonProfile.getAttribute(String)"?  Something like:

pac4jRealm.principalNameAttribute=display_name

If unspecified, the Pac4JPrincipal will return the id to maintain backwards compatibility.  How would you like to handle the misconfiguration case, where the supplied attribute name is not populated in the CommonProfile, so getAttribute returns null.  In that scenario, I think we should return the value of getId() to avoid returning null.  What do you think?

I'll put together a PR sometime this week.

**Comment by leleuj** [comment]
It's a fairly advanced use case, so let's keep that as simple as possible.

I agree with what you propose: `pac4jRealm.principalNameAttribute=display_name`. If it's set, we return the value (even if it's null (because of non-existing attribute)) or we return the identifier.

**Comment by HarvinderBhullar** [comment]
Hi @volumeint  could you share your shiro.ini for Zeppelin, which works against google openid.

**Comment by abdulwahid24** [comment]
@volumeint Good to see your solution. I am trying to do similar thing but I am unable to add buji-pac4j jars to the classpath. Would you please guide me to add buji-pac4j jars to the classpath.
Thanks
