### ISSUE TITLE
No subject alternative DNS name matching host.example.com

### ISSUE THREAD

**Issue by dannymk** [bujiio/buji-pac4j#64]
- Java:   jdk1.8.0_121
- pac4j-cas:   2.1.0
- pac4j-core:  2.1.0
- Shiro-core/web:  1.4.0

SSLPoke:  https://gist.github.com/4ndrej/4547029

The App server is using the following cert store:  cacerts.jks

java -Djavax.net.ssl.trustStore=cacerts.jks SSLPoke host.example.com 443
Successfully connected

However, just in case I also tested the certificates in /etc/...
java -Djavax.net.ssl.trustStore=keystore.jks SSLPoke host.example.com 443
Successfully connected

Every certificate store/file on the system has been tested for the certificate returned from the server yet in-spite of all my attempts I am still getting:

> [http-listener-1(1)] ERROR org.jasig.cas.client.util.CommonUtils - java.security.cert.CertificateException: No subject alternative DNS name matching host.example.com found.
> javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching host.example.com found.

I should mention that the certificate is a wildcard certificate ala "*.example.com"

shiro.ini 

```
[main]
casConfig = org.pac4j.cas.config.CasConfiguration
casConfig.loginUrl = https://host.example.com/cas/login
casClient = org.pac4j.cas.client.CasClient
casClient.configuration = $casConfig

clients.callbackUrl = http://myhost.example.com:8080/MyApp/callback
clients.clients = $casClient

requireRoleAdmin = org.pac4j.core.authorization.authorizer.RequireAnyRoleAuthorizer
requireRoleAdmin.elements = [administrator, cas_admin]

config.authorizers = admin:$requireRoleAdmin

casSecurityFilter = io.buji.pac4j.filter.SecurityFilter
casSecurityFilter.config = $config
casSecurityFilter.clients = CasClient

[urls]
/secure/** = casSecurityFilter
/callback = callbackFilter
/logout = logout
/** = anon
```
Every attempt at "/callback" fails with the mentioned error.  This seemed to be working properly a few version ago.  Not sure how to proceed at this point.

**Comment by leleuj** [comment]
Please ask your question on the mailing list to get help from other pac4j users.
