### ISSUE TITLE
Callbackfilter seems to break the filterchain

### ISSUE THREAD

**Issue by andre-doherty** [bujiio/buji-pac4j#66]
hello,

I have noticed that when the callback filter is executed, it doesn't continue the execution of the filterchain.
So only the CallbackFilter is executed and no further filters are triggred (the origin FilterChain stored in the ProxiedFilterChain is leftover).
Is that an issue or made by design ?

**Comment by leleuj** [comment]
Yes, this is by design: it finishes a login process for an indirect client (Facebook, CAS server, ...)

It doesn't make any sense to do something else at this stage.

**Comment by andre-doherty** [comment]
Well yes and no. 

I have some auditing filters that i would like to be triggered when the callback url is triggered.
But i could live with it.

The whole idea is more linked to the capability to do some SPA with a stateless Java backend (jaxrs1.1). 
As the profile is put in both request and session scope by the profileManager, i want to be able to stick to the request scope and send the SPA a jwt token using a filter triggered after the callback filter.

The other option would be to specialize the callback filter, but it looks a bit awkward to me.

**Comment by leleuj** [comment]
I see your point, I'm a bit worried that people start doing crazy stuff...

I opened this issue: https://github.com/bujiio/buji-pac4j/issues/67

The change is easy, I'll welcome your contribution. Thanks.
