### ISSUE TITLE
master branch is not compatible with pac4j 3.0

### ISSUE THREAD

**Issue by andre-doherty** [bujiio/buji-pac4j#71]
hello,

The current branch master is not compatible with the current master pac4j 3.0.0.

If backward compatibility is broken it might be a good idea to initiate a new branch to receive the adapted code.
I have already pushed a branch in my fork (branch evol-3.x) which worked successfully on my current project.

**Comment by leleuj** [comment]
Yes, this is completely on purpose. Here is the strategy: while the version 3.0.0-SNAPSHOT of pac4j is not stable, only the j2e-pac4j dependency is updated as much as possible. Then, when pac4j v3.0.0-SNAPSHOT will be close to the RC or GA, we'll start upgrading more and more pac4j implementations, starting with the more popular ones, like buji-pac4j...

**Comment by andre-doherty** [comment]
hello,

Thank you for the explanations.

Do you have an idea (roughly speaking) about when the 3.0.0 will be released ? 

As a matter of facts the changes i pulled on 2.2.x branches regarding the session management are a requirement for us (bnpp) to go live for several apps. Of course snapshot in production are prohibited.

Unless the timeframe to 3.0.0 is short enough i don't see much options but to create an artificial release which is something i would like to avoid

**Comment by leleuj** [comment]
Hard to say, there are only a few items I plan to integrate into the version 3.0.0, but I'm pretty busy and things can shift quickly.

But I have a solution for you: submit the same PR to the master, but change the current PR for the 2.2.x branch to make it backward compatible (turn the `saveInProfile`  input parameter into a property to keep the method signature and maybe some other adjustments). What do you think?

I reopened: https://github.com/pac4j/pac4j/pull/1089

**Comment by andre-doherty** [comment]
Thank you, that would be perfect to us.
I will try to figure out a solution in the next coming days.

i will also pull my changes on branch 3.0.0 (commit has been already done)

**Comment by jmesny** [comment]
Hello!
Is there any news on when a version compatible with pac4j 3.x would be released?

**Comment by leleuj** [comment]
I'll work on that in July when I come back from holidays...

**Comment by jmesny** [comment]
Thanks a lot, enjoy your holidays! :)
