### ISSUE TITLE
the Maven central repository  not to exists buji-pac4j 3.1.0

### ISSUE THREAD

**Issue by opqo** [bujiio/buji-pac4j#72]
![image](https://user-images.githubusercontent.com/12539738/35136561-42bf855e-fd1f-11e7-8213-3db3e2b125b6.png)

**Comment by leleuj** [comment]
Yes, I was too quick in changing the README. The release has not been cut yet, it's the 3.0.0-SNAPSHOT version, available in the Sonatype snapshots repository.
