### ISSUE TITLE
When an exception is throwed in a custom realm , this is still a  logged-in state. 

### ISSUE THREAD

**Issue by yxc023** [bujiio/buji-pac4j#75]
```
public class ShiroProfileManager extends ProfileManager<CommonProfile> {

    public ShiroProfileManager(final WebContext context) {
        super(context);
    }

    @Override
    public void save(final boolean saveInSession, final CommonProfile profile, final boolean multiProfile) {
        super.save(saveInSession, profile, multiProfile);

        ShiroHelper.populateSubject(retrieveAll(saveInSession));
    }
}
```
when `ShiroHelper.populateSubject()` executing, profile had been saved. 

I define a costom realm to get more authenticationInfo and authorizationInfo from another remote server.

Even though `ShiroHelper.populateSubject()` throw an AuthenticationException, when user visit my page again, pac4j treat him as logged in.

so  why not
```
@Override
public void save(final boolean saveInSession, final CommonProfile profile, final boolean multiProfile) {
    ShiroHelper.populateSubject(retrieveAll(saveInSession));

    super.save(saveInSession, profile, multiProfile);
}
```

**Comment by leleuj** [comment]
It makes sense, we could change that: we certainly should save the pac4j identity at the pac4j level only after the Shiro login has been successful.
What exception do you get for example? Thx

**Comment by yxc023** [comment]
When ShiroHelper.populateSubject() throw an AuthenticationException, user login  has bean successful in pac4j. But user does not logged in successfully in shiro.  
So when i visit my security page , i use shiro's `SecurityUtils.getSubject()` to get user profile, i get null.

An AuthenticationException should indicate a user do not login successfully.

**Comment by yxc023** [comment]
Glad to do that. A PR have been submited, check it pls.
