### ISSUE TITLE
It seems to me a bug...

### ISSUE THREAD

**Issue by 2301887641** [bujiio/buji-pac4j#76]
I am using version 3.0.0-RC1 of pac4j-jwt,version 3.2.0 of buji-pac4j.
I have the following error in ubuntu system: 
 Factory method 'shiroFilterFactoryBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/pac4j/core/http/HttpActionAdapter.

There is an error in io.buji.pac4j.filter.SecurityFilter's file.Program start error.

It seems to me a bug,  so I submit to you what I have discovered.

**Comment by leleuj** [comment]
It's not. buji-pac4j has not been upgraded to pac4j v3.x, you must use pac4j v2.x.
