### ISSUE TITLE
Exception when use shiro tag in jsp 

### ISSUE THREAD

**Issue by Seven4X** [bujiio/buji-pac4j#81]
javax.servlet.jsp.JspTagException: Property [sessionid] not found in principal of type [io.buji.pac4j.subject.Pac4jPrincipal]

version info : 
```
 <shiro.version>1.2.6</shiro.version>
  <pac4j.version>3.0.2</pac4j.version>
  <io.buji.version>4.0.0</io.buji.version>
```

jsp like this : 

```
<ul class="nav nav-tabs">
    <li><a href="${ctx}/base/xx">xxxx</a></li>
    <li class="active">
        <a href="${ctx}/base/>zzzz
            <shiro:hasPermission name="base:lqMixture:edit"> xxxxx</shiro:hasPermission>
            <shiro:lacksPermission name="base:lqMixture:edit">yyyyy</shiro:lacksPermission></a>
</li>
</ul>
```

my config like this : 

```
<bean id="securityManager" class="org.apache.shiro.web.mgt.DefaultWebSecurityManager">
        <property name="realm" ref="pac4jRealm"/>
        <property name="sessionManager" ref="sessionManager"/>
        <property name="cacheManager" ref="shiroCacheManager"/>
        <property name="rememberMeManager" ref="rememberMeManager"/>
        <property name="subjectFactory" ref="pac4jSubjectFactory"/>

    </bean>



``` 

I had a CustomAuthorizationGenerator config roles and Permissions.
my subject like this : 
![image](https://user-images.githubusercontent.com/1982168/48468714-9d95aa00-e827-11e8-9d99-3058564ccb97.png)

Is buji-pac4j support shiro tags ,or I should config something right to use it ?

**Comment by leleuj** [comment]
The truth is that I haven't tested the Shiro JSP tags with buji-pac4j so this might not be working. I would try with Shiro v1.4.0 just to be sure, but I think we need to do something to make it work. Any proposal? Thanks

**Comment by Seven4X** [comment]
the error appear after I wrroy used the shiro:principal tag.
```
<shiro:principal property="sessionid"/>
```
if I remove this tag ,all fine.
so this not buji-pac4j or buji-pac4j's bug . 
I feel I am so stupid. :cry:

**Comment by leleuj** [comment]
No problem. Thanks for the follow-up.
