### ISSUE TITLE
Update pac4j 3.4.0

### ISSUE THREAD

**Issue by tiboun** [bujiio/buji-pac4j#82]
Hi, can you please update pac4j in order to update my dependencies and fullfill a demand from https://github.com/apache/zeppelin/pull/3277. I could exclude pac4j dependencies and add my own but it would be better in my opinion to depends on a specific release and avoid as much as possible dependencies mistakes.

**Comment by leleuj** [comment]
Sure, it's better. I just released buji-pac4j v4.1.0 based on pac4j v3.4.0: it will show up in the Maven central repository within a few hours.
