### ISSUE TITLE
use optional Shiro bean as JEEHttpActionAdapter

### ISSUE THREAD

**Issue by shespelt** [bujiio/buji-pac4j#85]
Just a minor enhancement suggestion. I'm looking at, trying the Pac4j-core-4.0.0-SNAPSHOT code and it occured to me extra flexibility could be gained by using an optional JEEHttpActionAdapter bean rather than always using JEEHttpActionAdapter.INSTANCE - I have a case where I need to use a replacement for the INSTANCE default & it would helpful/useful to simply define the adapter in the shiro.ini rather than override all of doFilter() just to pass a different object.
It it helps, I could code it, test it.
-Steve

**Comment by leleuj** [comment]
Sure. We could do that relying on the `httpActionAdapter` available in the `Config`.

**Comment by leleuj** [comment]
Will be fixed in v5.0.0.
